### ISSUE TITLE
License

### ISSUE THREAD

**Issue by mnavasloro** [dhfbk/spanish#1]
Hello,

Thank you for sharing this code, it helped me a lot when using CoreNLP in Spanish. I would like to know what is the license of this code to reuse it.

Thank you and best regards,

María

**Comment by ziorufus** [comment]
Hello!
I'm glad you found this code useful. It has been written for an EU project that ended last year.
As it includes links to CoreNLP, I think I must release it under the "viral" GPLv3 license. If it's ok for you, consider it as GPL.

Best,
Alessio

**Comment by mnavasloro** [comment]
Perfect, thank you very much!

Best,
María
